#!/usr/bin/env bash

source "${0%/*}/utils/confirmation.sh"
source "${0%/*}/utils/configuration-report.sh"
source "${0%/*}/scripts/git-configure.sh"
source "${0%/*}/scripts/dotfiles-symlink.sh"
source "${0%/*}/scripts/environment-configure.sh"
source "${0%/*}/scripts/apps-install.sh"
source "${0%/*}/scripts/editor-packages-backup.sh"
source "${0%/*}/scripts/editor-configure.sh"
source "${0%/*}/scripts/macos-configure.sh"
source "${0%/*}/scripts/ssh-keys-restore.sh"

__help="
Dotfiles — A manager
Usage: dotfiles <command>

where <command> is one of:
  help              -   Displays this banner
  configure         -   Runs the entire configuration script on the host machine
  editor-backup     -   Backs up all atom packages to atom-packages.txt
  ssh-keys-restore  -   Sets up SSH keys permissions and adds primary identity to Keychain
"

__configure="
Dotfiles configuration

This command will go through a series of steps to configure the host machine's preferences, setup the development environment and install applications.
"

configure() {
  echo "$__configure"

  configuration-report "[1/6] 🔃 Git configuration" git-configure
  configuration-report "[2/6] 🔗 Symlink dotfiles" dotfiles-symlink
  configuration-report "[3/6] 🏗 Environment configuration" environment-configure
  configuration-report "[4/6] 📲 Apps installation" apps-install
  configuration-report "[5/6] ⌨️ Editor configuration" editor-configure
  configuration-report "[6/6] ⚙️ macOS preferences" macos-configure

  if ! confirm "🆗🎉  Do you want to restart now?"; then
    return 0
  fi

  sudo shutdown -r now
}

case "$1" in
  "help" | "-h")      echo "$__help";;
  "configure")        configure;;
  "editor-backup")    editor-packages-backup;;
  "ssh-keys-restore") ssh-keys-restore;;
  *)                  echo "$__help";;
esac
